services:
  - type: web
    name: fightev-backend
    env: python
    region: oregon
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    autoDeploy: true

  - type: web
    name: fightev-frontend
    env: node
    region: oregon
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npx serve -s dist -l $PORT
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_BACKEND_URL
        value: https://fightev-backend.onrender.com
    autoDeploy: true 