name: Update UFC Fight Card

on:
  schedule:
    - cron: '0 18 * * 6'  # Saturday at noon EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-card:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run card update script
        run: python backend/update_card.py
        env:
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add backend/data/card.json
          git commit -m "Saturday: update UFC fight card" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}